[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "claudius"
version = "0.1.0"
description = "A model harness like claudecode or codex built in python, supports Anthropic natively and a large amount of models via OpenRouter and Ollama"
license = "Apache-2.0"
license-files = ["LICENSE"]
requires-python = ">=3.10"
authors = [{ name = "Optccopa" }]
dependencies = [
    "anthropic",
    "rich",
    "httpx",
    "python-dotenv",
    "questionary",
    "platformdirs"
]

[project.scripts]
claudius = "claudius.cli:main"
 
[project.urls]
Repository = "https://github.com/Optccopa/claudius_harness"

[tool.setuptools.packages.find]
where = ["src"]